### ISSUE TITLE
No enchant glints?

### ISSUE THREAD

**Issue by HeatUp0** [Sharffffff/Mantori#7]
I've got this mod installed in a modpack i've made for myself, and I realized after a while that none of the enchant glints were showing up on items, I eventually through a long process of trial and error removing and adding mods found out this mod was the one causing the issue, and im pretty sure its unintentional but its a fairly big inconvenience anyways

**Comment by Sharffffff** [comment]
It is an intended behavior, making enchant glints a lot less intense. You can bring them back by putting fabric mod resource pack below the vanilla resource pack.
Glints make texture of the weapons and armor almost indistinguishable whenever they are at vanilla levels of intensity due to similar coloration and armor/weapons always being enchanted.
